server:
  port: 8888
spring:
  rabbitmq:
    host: 192.168.0.10
    username: pareZhang
    password: wxfyyzy115
    virtual-host: /pareZhang
    port: 5672
    publisher-confirms: true #开启confirm确认机制
    publisher-returns: true  #开启return确认机制
    template:
      mandatory: true   #设置为 true 后 消费者在消息没有被路由到合适队列情况下会被return监听，而不会自动删除